### ISSUE TITLE
Mac 版のハンズオンドキュメントの作成

### ISSUE THREAD

**Issue by fumiya-kume** [ayako/CognitiveXamarinHOL_201806#4]
Visual Studio for Mac の UI が Visual Studio for Window とかなり違います。
そのため、別個でドキュメント作ったほうがいいかと思います。
すでに大森さんのほうで作成されてますか？

**Comment by ayako** [comment]
作成次第Upします～

**Comment by ayako** [comment]
作成次第Upします～
