### ISSUE TITLE
Xamarin Part 2 のテキストのミスを発見

### ISSUE THREAD

**Issue by fumiya-kume** [ayako/CognitiveXamarinHOL_201806#6]
![2018-06-07 22 09 57](https://user-images.githubusercontent.com/16269075/41101625-9ae2b6dc-6a9f-11e8-8707-f6b76ad71726.png)

>RunButton_OnClicked は以下のように記述します。

と下に書かれている関数名が違っています。

**Comment by fumiya-kume** [comment]
https://github.com/fumiya-kume/CognitiveXamarinHOL_201806/blob/master/2_CognitiveXamarinAppDev_win02.md

**Comment by ayako** [comment]
Pull Request でいただけると助かります
